apiVersion: v1
data:
  htpasswd: *****
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"htpasswd":"******"},"kind":"Secret","metadata":{"annotations":{},"creationTimestamp":"2025-09-02T08:22:04Z","name":"htpass-secret","namespace":"openshift-config","resourceVersion":"51900","uid":"ba69d221-2306-4ada-b0b0-d7d5780cc645"},"type":"Opaque"}
  creationTimestamp: "2025-09-02T08:22:04Z"
  name: htpass-secret
  namespace: openshift-config
  resourceVersion: "53351"
  uid: ba69d221-2306-4ada-b0b0-d7d5780cc645
type: Opaque
