apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-helloworld
  namespace: stevenlab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-helloworld
  template:
    metadata:
      labels:
        app: springboot-helloworld
    spec:
      imagePullSecrets:
        - name: jfrog-pull
      containers:
        - name: app
          image: trialqdcy13.jfrog.io/stevenlab-docker-local/springboot-helloworld:1.0.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-helloworld
  namespace: stevenlab
spec:
  type: LoadBalancer
  selector:
    app: springboot-helloworld
  ports:
    - name: http
      port: 80
      targetPort: 8080
