apiVersion: apps/v1
kind: Deployment
metadata:
  name: boxes
  namespace: stevenlab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boxes
  template:
    metadata:
      labels:
        app: boxes
    spec:
      imagePullSecrets:
        - name: jfrog-pull
      containers:
        - name: boxes
          image: trialqdcy13.jfrog.io/stevenlab-docker-local/boxes:1.0
          ports:
            - containerPort: 8080   # ← 실제 리슨 포트에 맞춰 수정
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          # HTTP 경로가 불확실하므로 TCP 프로브로 안전하게 점검
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: boxes
  namespace: stevenlab
spec:
  type: LoadBalancer
  selector:
    app: boxes
  ports:
    - name: http
      port: 80
      targetPort: 8080   # ← 컨테이너 포트와 일치
